// Code generated by protoc-gen-go.
// source: ipersistence.proto
// DO NOT EDIT!

/*
Package ipersistence is a generated protocol buffer package.

It is generated from these files:
	ipersistence.proto

It has these top-level messages:
	FetchSaveRequest
	FetchSaveReply
	UpdateTagsRequest
	BaseResultReply
*/
package ipersistence

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type FetchSaveRequest struct {
	Url    string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	UserID string   `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Tags   []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *FetchSaveRequest) Reset()                    { *m = FetchSaveRequest{} }
func (m *FetchSaveRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSaveRequest) ProtoMessage()               {}
func (*FetchSaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FetchSaveRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FetchSaveRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *FetchSaveRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// The response message containing the greetings
type FetchSaveReply struct {
	ImageID string `protobuf:"bytes,1,opt,name=imageID" json:"imageID,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *FetchSaveReply) Reset()                    { *m = FetchSaveReply{} }
func (m *FetchSaveReply) String() string            { return proto.CompactTextString(m) }
func (*FetchSaveReply) ProtoMessage()               {}
func (*FetchSaveReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FetchSaveReply) GetImageID() string {
	if m != nil {
		return m.ImageID
	}
	return ""
}

func (m *FetchSaveReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type UpdateTagsRequest struct {
	ImageID string   `protobuf:"bytes,1,opt,name=imageID" json:"imageID,omitempty"`
	UserID  string   `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Tags    []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *UpdateTagsRequest) Reset()                    { *m = UpdateTagsRequest{} }
func (m *UpdateTagsRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTagsRequest) ProtoMessage()               {}
func (*UpdateTagsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateTagsRequest) GetImageID() string {
	if m != nil {
		return m.ImageID
	}
	return ""
}

func (m *UpdateTagsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateTagsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type BaseResultReply struct {
}

func (m *BaseResultReply) Reset()                    { *m = BaseResultReply{} }
func (m *BaseResultReply) String() string            { return proto.CompactTextString(m) }
func (*BaseResultReply) ProtoMessage()               {}
func (*BaseResultReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*FetchSaveRequest)(nil), "ipersistence.FetchSaveRequest")
	proto.RegisterType((*FetchSaveReply)(nil), "ipersistence.FetchSaveReply")
	proto.RegisterType((*UpdateTagsRequest)(nil), "ipersistence.UpdateTagsRequest")
	proto.RegisterType((*BaseResultReply)(nil), "ipersistence.BaseResultReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Saver service

type SaverClient interface {
	FetchSave(ctx context.Context, in *FetchSaveRequest, opts ...grpc.CallOption) (*FetchSaveReply, error)
	UpdateTags(ctx context.Context, in *UpdateTagsRequest, opts ...grpc.CallOption) (*BaseResultReply, error)
}

type saverClient struct {
	cc *grpc.ClientConn
}

func NewSaverClient(cc *grpc.ClientConn) SaverClient {
	return &saverClient{cc}
}

func (c *saverClient) FetchSave(ctx context.Context, in *FetchSaveRequest, opts ...grpc.CallOption) (*FetchSaveReply, error) {
	out := new(FetchSaveReply)
	err := grpc.Invoke(ctx, "/ipersistence.Saver/FetchSave", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saverClient) UpdateTags(ctx context.Context, in *UpdateTagsRequest, opts ...grpc.CallOption) (*BaseResultReply, error) {
	out := new(BaseResultReply)
	err := grpc.Invoke(ctx, "/ipersistence.Saver/UpdateTags", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Saver service

type SaverServer interface {
	FetchSave(context.Context, *FetchSaveRequest) (*FetchSaveReply, error)
	UpdateTags(context.Context, *UpdateTagsRequest) (*BaseResultReply, error)
}

func RegisterSaverServer(s *grpc.Server, srv SaverServer) {
	s.RegisterService(&_Saver_serviceDesc, srv)
}

func _Saver_FetchSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaverServer).FetchSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipersistence.Saver/FetchSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaverServer).FetchSave(ctx, req.(*FetchSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Saver_UpdateTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaverServer).UpdateTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipersistence.Saver/UpdateTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaverServer).UpdateTags(ctx, req.(*UpdateTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Saver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipersistence.Saver",
	HandlerType: (*SaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchSave",
			Handler:    _Saver_FetchSave_Handler,
		},
		{
			MethodName: "UpdateTags",
			Handler:    _Saver_UpdateTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipersistence.proto",
}

func init() { proto.RegisterFile("ipersistence.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x9b, 0x7f, 0xfe, 0x56, 0x32, 0x88, 0x36, 0x73, 0x90, 0x50, 0xac, 0x96, 0x3d, 0xf5,
	0x94, 0x83, 0x7a, 0xf6, 0x10, 0x8a, 0x10, 0x04, 0x09, 0x51, 0x0f, 0x1e, 0xd7, 0x38, 0xa4, 0x81,
	0xad, 0x59, 0x77, 0x36, 0x62, 0xbf, 0x8f, 0x1f, 0x54, 0xb2, 0xa4, 0xb6, 0xa9, 0xf4, 0xe0, 0xed,
	0xbd, 0xdd, 0x99, 0xc7, 0x6f, 0x66, 0x00, 0x2b, 0x4d, 0x86, 0x2b, 0xb6, 0xf4, 0x56, 0x50, 0xac,
	0x4d, 0x6d, 0x6b, 0x3c, 0xda, 0x7e, 0x13, 0x19, 0x8c, 0x6e, 0xc9, 0x16, 0x8b, 0x07, 0xf9, 0x41,
	0x39, 0xbd, 0x37, 0xc4, 0x16, 0x47, 0xe0, 0x37, 0x46, 0x45, 0xde, 0xd4, 0x9b, 0x05, 0x79, 0x2b,
	0xf1, 0x14, 0x86, 0x0d, 0x93, 0x49, 0xe7, 0xd1, 0x3f, 0xf7, 0xd8, 0x39, 0x44, 0xf8, 0x6f, 0x65,
	0xc9, 0x91, 0x3f, 0xf5, 0x67, 0x41, 0xee, 0xb4, 0xb8, 0x81, 0xe3, 0xad, 0x44, 0xad, 0x56, 0x18,
	0xc1, 0x61, 0xb5, 0x94, 0x25, 0xa5, 0xf3, 0x2e, 0x73, 0x6d, 0xdb, 0x7e, 0x2d, 0xed, 0xa2, 0x4b,
	0x75, 0x5a, 0x3c, 0x43, 0xf8, 0xa4, 0x5f, 0xa5, 0xa5, 0x47, 0x59, 0xf2, 0x1a, 0x69, 0x7f, 0xc4,
	0x5f, 0xd0, 0x42, 0x38, 0x49, 0x24, 0x53, 0x4e, 0xdc, 0x28, 0xeb, 0xd8, 0x2e, 0xbf, 0x3c, 0x38,
	0x68, 0x49, 0x0d, 0xde, 0x41, 0xf0, 0xc3, 0x8d, 0xe7, 0x71, 0x6f, 0x73, 0xbb, 0x2b, 0x1a, 0x9f,
	0xed, 0xfd, 0xd7, 0x6a, 0x25, 0x06, 0x78, 0x0f, 0xb0, 0x19, 0x02, 0x2f, 0xfa, 0xd5, 0xbf, 0xc6,
	0x1b, 0x4f, 0xfa, 0x05, 0x3b, 0x90, 0x62, 0x90, 0x5c, 0xc3, 0xa4, 0xaa, 0xe3, 0xd2, 0xe8, 0x22,
	0xa6, 0x4f, 0xb9, 0xd4, 0x8a, 0xb8, 0xd7, 0x92, 0x84, 0x69, 0xb6, 0x71, 0x59, 0x7b, 0xe8, 0xcc,
	0x7b, 0x19, 0xba, 0x8b, 0x5f, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x18, 0xd9, 0x52, 0x07,
	0x02, 0x00, 0x00,
}
