# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipersistence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ipersistence.proto',
  package='ipersistence',
  syntax='proto3',
  serialized_pb=_b('\n\x12ipersistence.proto\x12\x0cipersistence\"=\n\x10\x46\x65tchSaveRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06userID\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"Q\n\x0e\x46\x65tchSaveReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07imageID\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\"B\n\x11UpdateTagsRequest\x12\x0f\n\x07imageID\x18\x01 \x01(\t\x12\x0e\n\x06userID\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"D\n\x0f\x42\x61seResultReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07imageID\x18\x03 \x01(\t2\xa4\x01\n\x05Saver\x12K\n\tFetchSave\x12\x1e.ipersistence.FetchSaveRequest\x1a\x1c.ipersistence.FetchSaveReply\"\x00\x12N\n\nUpdateTags\x12\x1f.ipersistence.UpdateTagsRequest\x1a\x1d.ipersistence.BaseResultReply\"\x00\x42\x34\n\x1dio.grpc.examples.ipersistenceB\x11IPersistenceProtoP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FETCHSAVEREQUEST = _descriptor.Descriptor(
  name='FetchSaveRequest',
  full_name='ipersistence.FetchSaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='ipersistence.FetchSaveRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userID', full_name='ipersistence.FetchSaveRequest.userID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='ipersistence.FetchSaveRequest.tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=97,
)


_FETCHSAVEREPLY = _descriptor.Descriptor(
  name='FetchSaveReply',
  full_name='ipersistence.FetchSaveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ipersistence.FetchSaveReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='ipersistence.FetchSaveReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageID', full_name='ipersistence.FetchSaveReply.imageID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='ipersistence.FetchSaveReply.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=180,
)


_UPDATETAGSREQUEST = _descriptor.Descriptor(
  name='UpdateTagsRequest',
  full_name='ipersistence.UpdateTagsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageID', full_name='ipersistence.UpdateTagsRequest.imageID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userID', full_name='ipersistence.UpdateTagsRequest.userID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='ipersistence.UpdateTagsRequest.tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=248,
)


_BASERESULTREPLY = _descriptor.Descriptor(
  name='BaseResultReply',
  full_name='ipersistence.BaseResultReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ipersistence.BaseResultReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='ipersistence.BaseResultReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageID', full_name='ipersistence.BaseResultReply.imageID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=318,
)

DESCRIPTOR.message_types_by_name['FetchSaveRequest'] = _FETCHSAVEREQUEST
DESCRIPTOR.message_types_by_name['FetchSaveReply'] = _FETCHSAVEREPLY
DESCRIPTOR.message_types_by_name['UpdateTagsRequest'] = _UPDATETAGSREQUEST
DESCRIPTOR.message_types_by_name['BaseResultReply'] = _BASERESULTREPLY

FetchSaveRequest = _reflection.GeneratedProtocolMessageType('FetchSaveRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHSAVEREQUEST,
  __module__ = 'ipersistence_pb2'
  # @@protoc_insertion_point(class_scope:ipersistence.FetchSaveRequest)
  ))
_sym_db.RegisterMessage(FetchSaveRequest)

FetchSaveReply = _reflection.GeneratedProtocolMessageType('FetchSaveReply', (_message.Message,), dict(
  DESCRIPTOR = _FETCHSAVEREPLY,
  __module__ = 'ipersistence_pb2'
  # @@protoc_insertion_point(class_scope:ipersistence.FetchSaveReply)
  ))
_sym_db.RegisterMessage(FetchSaveReply)

UpdateTagsRequest = _reflection.GeneratedProtocolMessageType('UpdateTagsRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATETAGSREQUEST,
  __module__ = 'ipersistence_pb2'
  # @@protoc_insertion_point(class_scope:ipersistence.UpdateTagsRequest)
  ))
_sym_db.RegisterMessage(UpdateTagsRequest)

BaseResultReply = _reflection.GeneratedProtocolMessageType('BaseResultReply', (_message.Message,), dict(
  DESCRIPTOR = _BASERESULTREPLY,
  __module__ = 'ipersistence_pb2'
  # @@protoc_insertion_point(class_scope:ipersistence.BaseResultReply)
  ))
_sym_db.RegisterMessage(BaseResultReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035io.grpc.examples.ipersistenceB\021IPersistenceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class SaverStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.FetchSave = channel.unary_unary(
          '/ipersistence.Saver/FetchSave',
          request_serializer=FetchSaveRequest.SerializeToString,
          response_deserializer=FetchSaveReply.FromString,
          )
      self.UpdateTags = channel.unary_unary(
          '/ipersistence.Saver/UpdateTags',
          request_serializer=UpdateTagsRequest.SerializeToString,
          response_deserializer=BaseResultReply.FromString,
          )


  class SaverServicer(object):
    """The greeting service definition.
    """

    def FetchSave(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def UpdateTags(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SaverServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'FetchSave': grpc.unary_unary_rpc_method_handler(
            servicer.FetchSave,
            request_deserializer=FetchSaveRequest.FromString,
            response_serializer=FetchSaveReply.SerializeToString,
        ),
        'UpdateTags': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateTags,
            request_deserializer=UpdateTagsRequest.FromString,
            response_serializer=BaseResultReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ipersistence.Saver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSaverServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def FetchSave(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def UpdateTags(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSaverStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def FetchSave(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    FetchSave.future = None
    def UpdateTags(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    UpdateTags.future = None


  def beta_create_Saver_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('ipersistence.Saver', 'FetchSave'): FetchSaveRequest.FromString,
      ('ipersistence.Saver', 'UpdateTags'): UpdateTagsRequest.FromString,
    }
    response_serializers = {
      ('ipersistence.Saver', 'FetchSave'): FetchSaveReply.SerializeToString,
      ('ipersistence.Saver', 'UpdateTags'): BaseResultReply.SerializeToString,
    }
    method_implementations = {
      ('ipersistence.Saver', 'FetchSave'): face_utilities.unary_unary_inline(servicer.FetchSave),
      ('ipersistence.Saver', 'UpdateTags'): face_utilities.unary_unary_inline(servicer.UpdateTags),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Saver_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('ipersistence.Saver', 'FetchSave'): FetchSaveRequest.SerializeToString,
      ('ipersistence.Saver', 'UpdateTags'): UpdateTagsRequest.SerializeToString,
    }
    response_deserializers = {
      ('ipersistence.Saver', 'FetchSave'): FetchSaveReply.FromString,
      ('ipersistence.Saver', 'UpdateTags'): BaseResultReply.FromString,
    }
    cardinalities = {
      'FetchSave': cardinality.Cardinality.UNARY_UNARY,
      'UpdateTags': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'ipersistence.Saver', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
